name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  rxdart: ^0.27.7
  dio: ^5.1.1
  http: ^0.13.5
  cached_network_image: ^3.2.3
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Image_Logo02.png
    - assets/pngwingwomne.png
    - assets/women.jpg
    - assets/pngwing.png
